# RTWORKS clangd config file
# ln -s ~/dotfiles/scripts/rtworks/config.yaml ~/.config/clangd/config.yaml             # Linux
# ln -s ~/dotfiles/scripts/rtworks/config.yaml ~/Library/Preferences/clangd/config.yaml # macOS

CompileFlags:
  Remove: [
    -mabi=spe,
    -mcpu=e6500,
    -mno-unaligned-access,
    -mfloat-gprs=double
  ]

Diagnostics:
  Suppress: [
    pp_hash_error,
    pp_file_not_found,
    pp_including_mainfile_in_preamble,
    unknown_typename,
    unknown_typename_suggest,
    redefinition_different_typedef,
  ]
