# nerdfont-complete, lean, 1 line, info on the right

add_newline = false

format = "$character"

right_format = """
$os\
$hostname\
$directory\
$git_branch\
$git_status\
$docker_context\
$cmd_duration\
$jobs"""

[character]
success_symbol = "[❯](76)"
error_symbol = "[❯](196)"
vimcmd_symbol = "[❮](76)"
vimcmd_visual_symbol = "[V](76)"
vimcmd_replace_symbol = "[▶](76)"
vimcmd_replace_one_symbol = "[▶](76)"

[os]
disabled = false
format = "[$symbol]($style) "

[os.symbols]
Macos = ""
Linux = ""
Arch = ""
Debian = ""
Ubuntu = ""
Fedora = ""
Alpine = ""
CentOS = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
openSUSE = ""
SUSE = ""
NixOS = ""
Raspbian = ""
Manjaro = ""
Mint = ""
Pop = ""
Windows = ""

[hostname]
ssh_only = true
format = "[$hostname](180) "

[directory]
format = "[$path](31) "
truncation_length = 8
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
symbol = ""
format = "[$branch(:$remote_branch)](76) "

[git_status]
format = "$ahead_behind$stashed$conflicted$staged$modified$untracked"
ahead = "[⇡$count](76) "
behind = "[⇣$count](76) "
diverged = "[⇣${behind_count}⇡${ahead_count}](76) "
stashed = "[*$count](76) "
conflicted = "[~$count](196) "
staged = "[+$count](178) "
modified = "[!$count](178) "
untracked = "[?$count](39) "
deleted = ""
renamed = ""

[docker_context]
format = "[$context](39) "

[cmd_duration]
min_time = 3_000
format = "[$duration](101) "

[jobs]
format = "[$number](70) "
