#!/bin/bash

# cmd=$1
# if [ -z $cmd ]; then
#   cmd=r
# fi

# (echo $cmd | sudo cu -s 115200 -l /dev/cu.usbmodem14301 &) > /dev/null 2>&1

curl -fsSL "http://192.168.55.45/relay/0?turn=off"
sleep 0.3
curl -fsSL "http://192.168.55.45/relay/0?turn=on"
