-- extra highlight groups generated by Claude 3 Haiku
vim.api.nvim_set_hl(0, "St_warn_bg", { fg = "#1e222a", bg = "#d19a66" })
vim.api.nvim_set_hl(0, "St_warn_txt", { fg = "#d19a66", bg = "#282c34" })
vim.api.nvim_set_hl(0, "St_warn_sep", { fg = "#d19a66", bg = "#1e222a" })

vim.api.nvim_set_hl(0, "St_err_bg", { fg = "#1e222a", bg = "#e06c75" })
vim.api.nvim_set_hl(0, "St_err_txt", { fg = "#e06c75", bg = "#282c34" })
vim.api.nvim_set_hl(0, "St_err_sep", { fg = "#e06c75", bg = "#1e222a" })

vim.api.nvim_set_hl(0, "St_visual_bg", { fg = "#1e222a", bg = "#7b6df6" })
vim.api.nvim_set_hl(0, "St_visual_txt", { fg = "#7b6df6", bg = "#282c34" })
vim.api.nvim_set_hl(0, "St_visual_sep", { fg = "#7b6df6", bg = "#1e222a" })

vim.api.nvim_set_hl(0, "St_task_bg", { fg = "#1e222a", bg = "#61afef" })
vim.api.nvim_set_hl(0, "St_task_txt", { fg = "#61afef", bg = "#282c34" })
vim.api.nvim_set_hl(0, "St_task_sep", { fg = "#61afef", bg = "#1e222a" })

vim.api.nvim_set_hl(0, "St_debug_bg", { fg = "#1e222a", bg = "#c678dd" })
vim.api.nvim_set_hl(0, "St_debug_txt", { fg = "#c678dd", bg = "#282c34" })
vim.api.nvim_set_hl(0, "St_debug_sep", { fg = "#c678dd", bg = "#1e222a" })

