#!/bin/bash

# /opt/rtst/powerpc-unknown-elf/bin/powerpc-unknown-elf-objdump -dS ~/workspace/rtworks/builder/build.partition1/rtworks_partition.elf > ~/dumpinfo && vi ~/dumpinfo

# /opt/rtst/arm-none-eabi/bin/arm-none-eabi-objdump -dS ~/workspace/rtworks/builder/build.partition1/rtworks_partition.elf > ~/dumpinfo && vi ~/dumpinfo

# /opt/rtst/arm-none-eabi/bin/arm-none-eabi-objdump -dS ~/workspace/rtworks/builder/build.kernel/bootloader.elf > ~/dumpinfo && vi ~/dumpinfo

/opt/rtst/arm-none-eabi/bin/arm-none-eabi-objdump -dS ~/workspace/rtworks/builder/build.kernel/rtworks.elf > ~/dumpinfo && vi ~/dumpinfo
